"""Initial Migration

Revision ID: cf4e7963e6e3
Revises: 
Create Date: 2022-10-31 01:26:14.475042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4e7963e6e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=True, default=''))
    op.add_column('user', sa.Column('last_name', sa.String(length=30), nullable=True, default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
